cc_binary(
    name = 'game_svr',
    srcs = [
        "main.cpp",
        "game_server.cpp",
        "iomn_menu.cpp",
    ],

    incs = [
        '../../common/base',
    ],

    deps = [
        '//common/base:base',
    ],
)