cc_library(
    name = "network",
    srcs = [
        "teal_socket.cpp",
        "network_manager.cpp",
        "epoll_socket_listener.cpp",
    ],

    incs = [
        '../../common/base',
    ],

    deps = [
        '//common/base:base',
    ],
)